[Improvement] Added class to `tabBar`
pimcore/web-to-print-bundle pull request #38
Opened 2023-06-19 12:27 UTC by Corepex

Belongs To: https://github.com/pimcore/admin-ui-classic-bundle/pull/128

2023-06-19 12:37 UTC, blankse commented
If the CSS class is only added in Pimcore 11.1, we should also increase the version to 11.1 in composer.json

2023-06-19 12:39 UTC, blankse commented
If the CSS class is only added in pimcore/admin-ui-classic-bundle 1.1, we should also increase the version to 1.1 in composer.json

2023-08-22 06:30 UTC, robertSt7 requested changes

2023-08-22 06:30 UTC, robertSt7 commented on public/js/document/printcontainer.js
> +        return pimcore.helpers.getTabBar({items: items, defaults: {autoScroll:true}});
```suggestion
        this.tabbar = pimcore.helpers.getTabBar({items: items, defaults: {autoScroll:true}});
        return this.tabbar;
```

2023-08-22 06:30 UTC, robertSt7 commented on public/js/document/printpage.js
> +        return pimcore.helpers.getTabBar({items: items, defaults: {autoScroll:true}});
```suggestion
         this.tabbar = pimcore.helpers.getTabBar({items: items, defaults: {autoScroll:true}});
        return this.tabbar;
```

2023-08-24 15:30 UTC, merged